package com.example.groupcal.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This class is used to convert JSON data from the backend to [User] objects
 *
 * @param id The id generated in the backend defined by '_id' in JSON data
 * @param email The email address of the user defined by 'email' in JSON data
 * @param username The name of the user defined by 'username' in JSON data
 * @param phone The phone number of the user defined by 'phone' in JSON data
 * @param databaseId the id generated by the database
 *
 * @constructor Creates a new [User] object with the given parameters
 */
@JsonClass(generateAdapter = true)
data class User(
    @field:Json(name = "_id")
    val BackendId: String,
    @field:Json(name = "email")
    val email: String = "",
    @field:Json(name = "username")
    val username: String = "",
    @field:Json(name = "phone")
    val phone: String = "",
    val databaseId: Long = 0L
)